// import type { Metadata } from 'next';
// import '@/assets/styles/components/login.css';

// export const metadata: Metadata = {
//     title: 'Đăng nhập',
//     description: 'Generated by create next app',
// };

// export default function LoginLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         // <html lang="en">
//         //     <body className="bg_login">{children}</body>
//         // </html>
//         <div
//             style={{
//                 display: 'flex',
//                 flexDirection: 'column',
//                 alignItems: 'center',
//                 justifyContent: 'center',
//                 height: '100vh',
//             }}
//         >
//             <div
//                 style={{
//                     width: '100%',
//                     maxWidth: '400px',
//                     padding: '20px',
//                     boxShadow: '0px 0px 10px rgba(0,0,0,0.1)',
//                     borderRadius: '8px',
//                 }}
//             >
//                 {children} {/* Đây là nơi nội dung của `page.tsx` sẽ được render */}
//             </div>
//         </div>
//     );
// }
import '../globals.css';

export default function LoginLayout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            <div>{children}</div>
        </div>
    );
}
